Feat/set start order to init
weseek/angular-custom-tour pull request #2
Opened 2019-05-15 12:57 UTC by haruhikonyan

2019-05-15 13:08 UTC, yuki-takei requested changes

2019-05-15 13:08 UTC, yuki-takei commented on README.md
> +  }
このインデントはなんだ？

2019-05-15 13:08 UTC, yuki-takei commented on README.md
> +  }
> set order number second argument 

set order number as the second argument

2019-05-15 13:08 UTC, yuki-takei commented on src/hint.service.ts
> +    if (startStepIndex === -1) {
index 系のチェックは `if (startStepIndex < 0)` が一般的かなあ。細かいけど。

2019-05-15 13:08 UTC, yuki-takei commented on src/hint.service.ts
> +  public initialize(options: HintOptions = null, startOrder: number = null): void {
`= null` 書かなくていいんじゃ？

2019-05-15 13:08 UTC, yuki-takei commented on src/hint.service.ts
> +    let startStepIndex: number = this.steps.findIndex((step: Step) => step.order === startOrder);
`startOrder` が null なら `findIndex` 処理自体やらずに 0 で初期化すればよくない？

2019-05-16 01:44 UTC, haruhikonyan commented on src/hint.service.ts
> +  public initialize(options: HintOptions = null, startOrder: number = null): void {
これ無いと `this.hintService.initialize();` 引数無しで HintOptions デフォルトで使ってる人たちが動かなくなるよね？

2019-05-16 01:45 UTC, haruhikonyan commented on src/hint.service.ts
> +    let startStepIndex: number = this.steps.findIndex((step: Step) => step.order === startOrder);
startOrder に無いものを入力した場合に 0 が代入されるようにしたほうがいいかなと思ったけど
エラー出して動かなくしちゃったほうがいいのかなぁ？

2019-05-16 01:50 UTC, haruhikonyan commented on README.md
> +  }
# Custom options Usage
の欄にも謎インデントついてるね
必ず init の中とかに書かれるからトップレベルではありえないからこうなってるのかな説
ま、消しとくか

2019-05-16 13:05 UTC, yuki-takei requested changes

2019-05-16 13:05 UTC, yuki-takei commented on src/hint.service.ts
> +    let startStepIndex: number = this.steps.findIndex((step: Step) => step.order === startOrder);
サービス層というのを鑑みればその挙動も全然あり。

2019-05-16 13:05 UTC, yuki-takei commented on src/hint.service.ts
> +  public initialize(options: HintOptions = null, startOrder: number = null): void {
```
public initialize(options: HintOptions, startOrder: number): void {
  this.hintOptions = options || new HintOptions();
```

これで 31～34 行目は不要。

2019-05-17 09:30 UTC, merged